### ISSUE TITLE
Questions about training detailes

### ISSUE THREAD

**Issue by wayne391** [sakemin/cog-musicgen-chord#1]
Hi, thanks for sharing this awesome work! A generative music model with a chord control is definitely a huge progress.

Currently I am trying to train the model by myself with my own data. Here are some questions:

1. Which dataset did you use? If it cannot be revealed, could you describe the approximate size the data?
2. Did you fine-tined the musicgen-chord from scratch? If not, I saw there's a part for fine-tuning, but there's no description about which MusicGen model you used (maybe it's fine-tuned from melody model). Is the fine-tuning instructions for training on current model or training on Meta's MusicGen model?
3. If the musicgen-chord model is trained from scratch, could you share that how long it took and what machines did you use? 

Looking forward to your reply :3

**Comment by sakemin** [comment]
Hello @wayne391 !
Thanks for asking! Here are the answers for your questions.

1. The model is not actually fine-tuned. The model weights are brought from Meta's MusicGen-Melody model. I just tweaked the melody conditioning part by re-purposing the one-hot melody condition vectors into multi-hot chord condition vectors.
2. 3. The answer above might be the answers these question too.

You can check [the blog post about MusicGen-Chord](https://replicate.com/blog/generate-music-from-chord-progressions-musicgen-chord). There are more implementaion details here.

Thanks!
Sake
