### ISSUE TITLE
publish latest to replicate?

### ISSUE THREAD

**Issue by yocontra** [sakemin/cog-musicgen-chord#2]
Looks like the last deploy to replicate was on november 7 (https://github.com/sakemin/cog-musicgen-chord/commit/6674ff554e14d3b639554b2e17ab58bd42ce82f6), lots of nice new changes since then that would be nice to use on replicate (like specifying model version). Thanks!

**Comment by sakemin** [comment]
Hello @yocontra !
New models of audiocraft(eg. stereo models) are implemented as a separate replicate model, [sakemin/musicgen-stereo-chord](https://replicate.com/sakemin/musicgen-stereo-chord).
I will also push the model on github as a repo soon.
